[workspace]

# honestly, i dont know what difference this makes compared to auto, but it makes the compiler shut up, sooooooooooooooooooooo
resolver = "2"

members = [ "game","paper", "pencil", "person"]

[profile.release]
debug = true
